import type { McqItem } from './types';

/**
 * Banca delle crocette, raggruppate per argomento.
 *
 * PER AGGIUNGERE UNA DOMANDA: copia una voce nella sezione giusta, dàlle un
 * `id` non usato, scrivi le 4 alternative in `options` e metti in `correct`
 * l'indice (0-based) di quella esatta. Il motore rimescola le alternative a
 * ogni generazione, quindi l'ordine che scrivi qui non conta.
 *
 * `q` e `options` accettano markup inline (<b>, <code>).
 */
export const mcq: McqItem[] = [
  // ══════════════════ Algebra di Boole & porte ══════════════════
  {
    id: 'mcq-bool-01',
    topic: 'bool',
    q: "Quali operatori rendono l'algebra di Boole funzionalmente completa da soli?",
    options: ['AND e OR', 'NAND e NOR', 'NOT e AND', 'XOR e OR'],
    correct: 1,
  },
  {
    id: 'mcq-bool-02',
    topic: 'bool',
    q: 'Con soli AND e OR, perché non si sintetizza ogni funzione?',
    options: ['Manca la negazione', 'Sono troppo lenti', 'Non sono associativi', 'Consumano troppo'],
    correct: 0,
  },
  {
    id: 'mcq-bool-03',
    topic: 'bool',
    q: 'Quale porta logica si ottiene combinando due NAND?',
    options: ['OR', 'AND', 'NOR', 'XNOR'],
    correct: 1,
  },

  {
    id: 'mcq-bool-04',
    topic: 'bool',
    q: 'Per il teorema di assorbimento, <code>A ∨ (A ∧ B)</code> equivale a:',
    options: ['A', 'B', 'A ∧ B', 'A ⊕ B'],
    correct: 0,
  },
  {
    id: 'mcq-bool-05',
    topic: 'bool',
    q: 'In una forma canonica SOP, quanti mintermini si scrivono?',
    options: [
      'Uno per ogni riga della tabella con uscita 1',
      'Uno per ogni riga della tabella con uscita 0',
      'Uno per ogni variabile',
      'Sempre quattro',
    ],
    correct: 0,
  },
  {
    id: 'mcq-bool-06',
    topic: 'bool',
    q: 'Quanto vale <code>A ⊕ A</code>?',
    options: ['0', '1', 'A', 'NOT A'],
    correct: 0,
  },

  // ══════════════════ Sintesi & mappe di Karnaugh ══════════════════
  {
    id: 'mcq-karnaugh-01',
    topic: 'karnaugh',
    q: 'In quale ordine si dispongono le colonne di una mappa di Karnaugh?',
    options: ['00, 01, 10, 11', '00, 01, 11, 10', '11, 10, 01, 00', "L'ordine è indifferente"],
    correct: 1,
  },
  {
    id: 'mcq-karnaugh-02',
    topic: 'karnaugh',
    q: 'Quale dimensione NON può avere un gruppo in una mappa di Karnaugh?',
    options: ['2', '4', '6', '8'],
    correct: 2,
  },
  {
    id: 'mcq-karnaugh-03',
    topic: 'karnaugh',
    q: 'Un implicante primo si dice <b>essenziale</b> quando:',
    options: [
      'È il gruppo più grande della mappa',
      "Copre almeno un 1 che nessun altro implicante primo copre",
      'Contiene almeno una indifferenza',
      'Ha un solo letterale',
    ],
    correct: 1,
  },
  {
    id: 'mcq-karnaugh-04',
    topic: 'karnaugh',
    q: 'Come si trattano le indifferenze (x) in una mappa?',
    options: [
      'Si pongono tutte a 1',
      'Si pongono tutte a 0',
      'Si valutano una per una, prendendole a 1 solo se allargano un gruppo',
      'Si escludono dalla mappa',
    ],
    correct: 2,
  },

  // ══════════════════ Numeri binari & complemento a 2 ══════════════════
  {
    id: 'mcq-bin-01',
    topic: 'bin',
    q: 'La base del sistema numerico Maya è:',
    options: ['10 (decimale)', '20 (vigesimale)', '16 (esadecimale)', '8 (ottale)'],
    correct: 1,
  },
  {
    id: 'mcq-bin-02',
    topic: 'bin',
    q: 'Uno shift a sinistra di un intero equivale a:',
    options: ['Divisione per 2', 'Moltiplicazione per 2', 'Negazione', 'Complemento a 1'],
    correct: 1,
  },
  {
    id: 'mcq-bin-03',
    topic: 'bin',
    q: 'Quali rappresentazioni hanno due codifiche dello zero?',
    options: ['CP2', 'Senza segno', 'Complemento a 1 e modulo-e-segno', 'Esadecimale'],
    correct: 2,
  },
  {
    id: 'mcq-bin-04',
    topic: 'bin',
    q: 'Eliminare il bit meno significativo di un intero senza segno equivale a:',
    options: ['Moltiplicare per 2', 'Dividere (intero) per 2', 'Negare', 'Nulla'],
    correct: 1,
  },
  {
    id: 'mcq-bin-05',
    topic: 'bin',
    q: 'In una rappresentazione Big Endian, il bit di segno si trova:',
    options: [
      'Alla fine',
      "All'inizio (byte più significativo)",
      'Al centro',
      'In un registro a parte',
    ],
    correct: 1,
  },
  {
    id: 'mcq-bin-06',
    topic: 'bin',
    q: 'Quante cifre esadecimali servono per rappresentare 33?',
    options: ['1', '2', '3', '4'],
    correct: 1,
  },
  {
    id: 'mcq-bin-07',
    topic: 'bin',
    q: "Quale porta rileva l'overflow sommando due numeri con n bit?",
    options: ['AND', 'OR', 'XOR', 'NAND'],
    correct: 2,
  },
  {
    id: 'mcq-bin-08',
    topic: 'bin',
    q: 'Come ti accorgi di un overflow sommando due positivi in CP2?',
    options: [
      'Ottieni un numero negativo',
      'Ottieni zero',
      'Il risultato raddoppia',
      'Nessun segnale',
    ],
    correct: 0,
  },
  {
    id: 'mcq-bin-09',
    topic: 'bin',
    q: "In CP2 l'overflow può verificarsi nella:",
    options: [
      'Somma di due discordi',
      'Sottrazione di due discordi',
      'Somma con lo zero',
      'Divisione',
    ],
    correct: 1,
  },

  {
    id: 'mcq-bin-10',
    topic: 'bin',
    q: 'Per estendere <code>1011</code> (CP2 su 4 bit) a 8 bit si deve:',
    options: [
      'Aggiungere zeri a sinistra → 00001011',
      'Replicare il bit di segno → 11111011',
      'Aggiungere zeri a destra → 10110000',
      'Invertire i bit e sommare 1',
    ],
    correct: 1,
  },
  {
    id: 'mcq-bin-11',
    topic: 'bin',
    q: 'Per dividere per 2 un numero negativo in CP2 serve uno shift a destra:',
    options: [
      'Logico (entra 0 da sinistra)',
      'Aritmetico (replica il bit di segno)',
      'Circolare',
      'A sinistra',
    ],
    correct: 1,
  },
  {
    id: 'mcq-bin-12',
    topic: 'bin',
    q: 'In CP2 su N bit, quale peso ha il bit più significativo?',
    options: ['+2ᴺ⁻¹', '−2ᴺ⁻¹', '+1', 'Nessuno: indica solo il segno'],
    correct: 1,
  },

  // ══════════════════ Circuiti sequenziali ══════════════════
  {
    id: 'mcq-ff-01',
    topic: 'ff',
    q: "Che cos'è un flip-flop?",
    options: [
      'Un registro a 8 bit',
      'Un elemento bistabile che memorizza 1 bit',
      'Una porta logica universale',
      'Un tipo di bus',
    ],
    correct: 1,
  },
  {
    id: 'mcq-ff-02',
    topic: 'ff',
    q: 'Un flip-flop master-slave è di tipo:',
    options: ['Asincrono', 'Sincrono (edge-triggered)', 'Combinatorio', 'Analogico'],
    correct: 1,
  },

  {
    id: 'mcq-ff-03',
    topic: 'ff',
    q: 'In un latch SR realizzato con NOR, quale combinazione è proibita?',
    options: ['S=0, R=0', 'S=1, R=0', 'S=0, R=1', 'S=1, R=1'],
    correct: 3,
  },
  {
    id: 'mcq-ff-04',
    topic: 'ff',
    q: 'Un flip-flop JK con <code>J=K=1</code> sul fronte di clock:',
    options: ['Mantiene lo stato', 'Va a 1', 'Va a 0', 'Commuta (toggle)'],
    correct: 3,
  },
  {
    id: 'mcq-ff-05',
    topic: 'ff',
    q: 'Quale flip-flop è il mattone naturale di un contatore?',
    options: ['Tipo T', 'Tipo D', 'Latch SR', 'Nessuno: servono solo porte AND'],
    correct: 0,
  },
  {
    id: 'mcq-ff-06',
    topic: 'ff',
    q: 'Svantaggio principale di un contatore asincrono (ripple) rispetto a uno sincrono:',
    options: [
      'Richiede più flip-flop',
      'I ritardi si accumulano e le uscite non cambiano tutte insieme',
      'Non può contare oltre 8',
      'Necessita di un clock più lento del sincrono per definizione',
    ],
    correct: 1,
  },

  // ══════════════════ Processore: datapath & controllo ══════════════════
  {
    id: 'mcq-cpu-01',
    topic: 'cpu',
    q: 'Quale registro presenta alla memoria l’indirizzo a cui accedere?',
    options: ['MDR', 'MAR', 'IR', 'PC'],
    correct: 1,
  },
  {
    id: 'mcq-cpu-02',
    topic: 'cpu',
    q: 'Quale registro trattiene l’istruzione durante la decodifica?',
    options: ['PC', 'MAR', 'IR', 'MDR'],
    correct: 2,
  },
  {
    id: 'mcq-cpu-03',
    topic: 'cpu',
    q: 'Perché il PC viene incrementato subito dopo il prelievo?',
    options: [
      "Perché l'esecuzione è sequenziale e l'indirizzo successivo è così già pronto",
      'Perché altrimenti si perderebbe il contenuto di IR',
      'Per azzerare i flag della ALU',
      'Per liberare il bus dati',
    ],
    correct: 0,
  },
  {
    id: 'mcq-cpu-04',
    topic: 'cpu',
    q: "Vantaggio di un'unità di controllo microprogrammata rispetto a una cablata:",
    options: [
      'È sempre più veloce',
      'Consuma meno energia',
      "È più flessibile: cambiare l'insieme di istruzioni non richiede di riprogettare il circuito",
      'Non richiede segnali di clock',
    ],
    correct: 2,
  },
  {
    id: 'mcq-cpu-05',
    topic: 'cpu',
    q: 'Cosa permette un datapath a tre bus rispetto a uno a bus singolo?',
    options: [
      'Indirizzare più memoria',
      "Portare entrambi gli operandi alla ALU e scrivere il risultato nello stesso ciclo",
      'Eliminare del tutto la necessità di registri',
      'Eseguire istruzioni di lunghezza variabile',
    ],
    correct: 1,
  },

  // ══════════════════ RISC/CISC & assembly ══════════════════
  {
    id: 'mcq-isa-01',
    topic: 'isa',
    q: 'RISC sta per:',
    options: [
      'Reduced Instruction Set Computing',
      'Rapid Internal Signal Control',
      'Random Instruction Sequence Computing',
      'Reduced Internal Storage Cache',
    ],
    correct: 0,
  },
  {
    id: 'mcq-isa-02',
    topic: 'isa',
    q: "Caratteristica tipica di un'architettura RISC:",
    options: [
      'Istruzioni di lunghezza variabile',
      'Operazioni memoria-memoria',
      'Modello load/store con istruzioni a lunghezza fissa',
      'Nessuna pipeline',
    ],
    correct: 2,
  },
  {
    id: 'mcq-isa-03',
    topic: 'isa',
    q: 'In <code>Add R1,R2,R3</code>, dove finisce il risultato?',
    options: ['In R2', 'In R3', 'In R1', 'In memoria LOC'],
    correct: 2,
  },
  {
    id: 'mcq-isa-04',
    topic: 'isa',
    q: 'Il loader si occupa principalmente di:',
    options: [
      'Compilare il codice',
      'Caricare programmi in memoria (e dello spiazzamento)',
      'Gestire gli interrupt',
      'Sostituire i blocchi cache',
    ],
    correct: 1,
  },
  {
    id: 'mcq-isa-05',
    topic: 'isa',
    q: 'Il linker serve a:',
    options: [
      'Tradurre in linguaggio macchina',
      'Combinare più file oggetto risolvendo i riferimenti esterni',
      'Gestire la memoria virtuale',
      'Cancellare la EPROM',
    ],
    correct: 1,
  },
  {
    id: 'mcq-isa-06',
    topic: 'isa',
    q: 'Chi traduce il codice sorgente in linguaggio macchina?',
    options: ['Il sistema operativo', 'Il compilatore', 'Il loader', 'La ALU'],
    correct: 1,
  },
  {
    id: 'mcq-isa-07',
    topic: 'isa',
    q: 'Quale istruzione ARM trasferisce un valore da un registro a un altro?',
    options: ['CMP', 'ADD', 'SUB', 'MOV'],
    correct: 3,
  },
  {
    id: 'mcq-isa-08',
    topic: 'isa',
    q: 'Quale istruzione realizza un salto condizionato «se maggiore»?',
    options: ['BGT', 'MOV', 'MUL', 'CLR'],
    correct: 0,
  },

  {
    id: 'mcq-isa-09',
    topic: 'isa',
    q: 'In <code>Load R1, 8(R2)</code>, quale modo di indirizzamento è usato?',
    options: ['Immediato', 'Assoluto', 'Indicizzato (base + spiazzamento)', 'Relativo al PC'],
    correct: 2,
  },
  {
    id: 'mcq-isa-10',
    topic: 'isa',
    q: 'Perché un solo link register non basta per i sottoprogrammi ricorsivi?',
    options: [
      'Perché è troppo piccolo per un indirizzo',
      "Perché una nuova chiamata ne sovrascrive l'indirizzo di ritorno",
      'Perché non è accessibile in lettura',
      'Perché va azzerato a ogni salto',
    ],
    correct: 1,
  },
  {
    id: 'mcq-isa-11',
    topic: 'isa',
    q: 'Che cosa fa tipicamente l’istruzione <code>CMP</code>?',
    options: [
      'Salta se i due operandi sono uguali',
      'Copia un registro in un altro',
      'Esegue una sottrazione aggiornando i flag senza salvare il risultato',
      'Confronta e scambia due registri',
    ],
    correct: 2,
  },
  {
    id: 'mcq-isa-12',
    topic: 'isa',
    q: 'In quale direzione cresce tipicamente la pila?',
    options: [
      'Verso gli indirizzi bassi',
      'Verso gli indirizzi alti',
      'Non cresce: ha dimensione fissa',
      'Dipende dal valore del PC',
    ],
    correct: 0,
  },

  // ══════════════════ Interruzioni, eccezioni, I/O ══════════════════
  {
    id: 'mcq-irq-01',
    topic: 'irq',
    q: 'Le interruzioni hardware sono eventi:',
    options: ['Sincroni', 'Asincroni', 'Deterministici sul clock', 'Generati dalla ALU'],
    correct: 1,
  },
  {
    id: 'mcq-irq-02',
    topic: 'irq',
    q: 'Le eccezioni sono generate:',
    options: [
      'Da dispositivi esterni',
      "Dal processore durante l'esecuzione",
      'Solo dalla tastiera',
      'Dal bus dati',
    ],
    correct: 1,
  },
  {
    id: 'mcq-irq-03',
    topic: 'irq',
    q: 'Le richieste di interruzione viaggiano su quali linee del bus?',
    options: ['Linee dati', 'Linee indirizzi', 'Linee di controllo', 'Linee di alimentazione'],
    correct: 2,
  },
  {
    id: 'mcq-irq-04',
    topic: 'irq',
    q: "La <b>trace mode</b> del debugger genera un'interruzione:",
    options: ['A ogni breakpoint', 'Dopo ogni istruzione', 'A fine programma', 'Mai'],
    correct: 1,
  },
  {
    id: 'mcq-irq-05',
    topic: 'irq',
    q: 'Chi gestisce la scrittura sulla memoria di massa?',
    options: ['La cache', 'Il sistema operativo', 'Il compilatore', 'Il registro PC'],
    correct: 1,
  },
  {
    id: 'mcq-irq-06',
    topic: 'irq',
    q: 'Quale meccanismo compensa la differenza di velocità tra due dispositivi?',
    options: ['Il buffer', 'La ALU', 'Il PC', 'Il flip-flop'],
    correct: 0,
  },
  {
    id: 'mcq-irq-07',
    topic: 'irq',
    q: "Un'eccezione è sollevata se un processo tenta di…",
    options: [
      'Modificare la priorità di altri processi',
      'Accedere alla memoria di altri utenti',
      'Modificare la modalità del sistema',
      'Tutte le precedenti',
    ],
    correct: 3,
  },
  {
    id: 'mcq-irq-08',
    topic: 'irq',
    q: 'Gli interrupt sono particolarmente importanti nei sistemi:',
    options: ['Batch', 'Real-time', 'A singolo task', 'Analogici'],
    correct: 1,
  },
  {
    id: 'mcq-irq-09',
    topic: 'irq',
    q: 'Le interruzioni sono fondamentali per i sistemi:',
    options: ['Monotasking', 'Multitasking', 'Combinatori', 'Puramente sincroni'],
    correct: 1,
  },
  {
    id: 'mcq-irq-10',
    topic: 'irq',
    q: 'Cosa viene trasportato da un bus?',
    options: [
      'Solo dati',
      'Solo indirizzi',
      'Dati, indirizzi e segnali di controllo',
      'Solo controlli',
    ],
    correct: 2,
  },
  {
    id: 'mcq-irq-11',
    topic: 'irq',
    q: 'Come vengono trasmessi i dati su USB?',
    options: ['In parallelo', 'In modo seriale', 'Solo in analogico', 'Sul bus indirizzi'],
    correct: 1,
  },

  {
    id: 'mcq-irq-12',
    topic: 'irq',
    q: 'Nelle interruzioni <b>vettorializzate</b>, come si individua la routine da eseguire?',
    options: [
      'Interrogando i dispositivi uno per uno',
      'Il dispositivo fornisce un identificatore che indicizza la tabella dei vettori',
      'Si esegue sempre la stessa routine',
      "Lo decide l'utente a runtime",
    ],
    correct: 1,
  },
  {
    id: 'mcq-irq-13',
    topic: 'irq',
    q: 'Vantaggio principale del DMA:',
    options: [
      'Riduce la dimensione della memoria necessaria',
      'Trasferisce blocchi fra periferica e memoria senza impegnare il processore',
      'Elimina la necessità di interruzioni',
      'Aumenta la frequenza di clock',
    ],
    correct: 1,
  },
  {
    id: 'mcq-irq-14',
    topic: 'irq',
    q: "Quando arriva una richiesta di interruzione, il processore:",
    options: [
      "Interrompe immediatamente l'istruzione in corso, a metà",
      "Termina l'istruzione in corso, poi salva lo stato",
      'Attende la fine del programma',
      'Ignora la richiesta se sta eseguendo un salto',
    ],
    correct: 1,
  },

  // ══════════════════ Pipeline & prestazioni ══════════════════
  {
    id: 'mcq-pipe-01',
    topic: 'pipe',
    q: 'Il miglioramento del pipelining deriva da:',
    options: [
      'Clock più veloce',
      'Sovrapposizione (parallelismo) delle fasi delle istruzioni',
      'Meno registri',
      'Cache più grande',
    ],
    correct: 1,
  },
  {
    id: 'mcq-pipe-02',
    topic: 'pipe',
    q: 'La dipendenza dai dati in pipeline si mitiga con:',
    options: [
      'Operand forwarding',
      'Aumento del clock',
      'Riduzione dei registri',
      'Disattivare la cache',
    ],
    correct: 0,
  },
  {
    id: 'mcq-pipe-05',
    topic: 'pipe',
    q: 'Quale hazard nasce dal fatto che dopo un salto non si sa quale istruzione prelevare?',
    options: ['Strutturale', 'Sui dati', 'Di controllo', 'Di parità'],
    correct: 2,
  },
  {
    id: 'mcq-pipe-06',
    topic: 'pipe',
    q: 'Nella formula <code>T = (N × S) / R</code>, che cosa rappresenta <code>S</code>?',
    options: [
      'La frequenza di clock',
      'I cicli di clock medi per istruzione (CPI)',
      'Il numero di stadi della pipeline',
      'La dimensione della cache',
    ],
    correct: 1,
  },
  {
    id: 'mcq-pipe-07',
    topic: 'pipe',
    q: 'Con una pipeline a k stadi, lo speedup ideale rispetto al caso non pipelined è:',
    options: ['2', 'k', 'k²', 'Indipendente da k'],
    correct: 1,
  },
  {
    id: 'mcq-pipe-08',
    topic: 'pipe',
    q: 'Il pipelining migliora soprattutto:',
    options: [
      'La latenza della singola istruzione',
      'Il throughput, cioè le istruzioni completate per unità di tempo',
      'La dimensione del codice',
      'Il consumo energetico',
    ],
    correct: 1,
  },

  // ══════════════════ Processore: prestazioni e ALU ══════════════════
  {
    id: 'mcq-pipe-03',
    topic: 'cpu',
    q: 'Le prestazioni del processore dipendono dalla velocità di:',
    options: [
      'Solo esecuzione',
      'Prelievo (fetch) ed esecuzione',
      'Solo decodifica',
      'Solo scrittura',
    ],
    correct: 1,
  },
  {
    id: 'mcq-pipe-04',
    topic: 'cpu',
    q: 'Dove salva la ALU i risultati intermedi di un calcolo?',
    options: ['In cache', 'Nei registri', 'In memoria secondaria', 'Nel PC'],
    correct: 1,
  },

  // ══════════════════ Memoria & cache ══════════════════
  {
    id: 'mcq-mem-01',
    topic: 'mem',
    q: "Che cos'è un cache <b>miss</b>?",
    options: [
      'Il dato è in cache',
      'Il dato non è in cache e si scende nella gerarchia',
      'La cache è piena',
      'Un errore di parità',
    ],
    correct: 1,
  },
  {
    id: 'mcq-mem-02',
    topic: 'mem',
    q: 'Il ritardo introdotto dopo un cache miss si chiama:',
    options: ['hit ratio', 'miss penalty', 'write-back', 'latch delay'],
    correct: 1,
  },
  {
    id: 'mcq-mem-03',
    topic: 'mem',
    q: 'Quali proprietà sfrutta la cache?',
    options: [
      'Solo temporale',
      'Solo spaziale',
      'Località spaziale e temporale',
      'Nessuna delle due',
    ],
    correct: 2,
  },
  {
    id: 'mcq-mem-04',
    topic: 'mem',
    q: 'Algoritmo di sostituzione più comune in cache:',
    options: ['FIFO', 'LRU', 'Random', 'MRU'],
    correct: 1,
  },
  {
    id: 'mcq-mem-05',
    topic: 'mem',
    q: 'La EPROM si cancella:',
    options: [
      'Elettricamente',
      'Con raggi ultravioletti',
      'Meccanicamente',
      'Non si cancella',
    ],
    correct: 1,
  },
  {
    id: 'mcq-mem-06',
    topic: 'mem',
    q: 'La EEPROM si cancella:',
    options: ['Con raggi UV', 'Elettricamente', 'Termicamente', 'Con luce visibile'],
    correct: 1,
  },
  {
    id: 'mcq-mem-07',
    topic: 'mem',
    q: 'La memoria cache è tipicamente realizzata con:',
    options: ['DRAM', 'SRAM', 'EEPROM', 'Disco'],
    correct: 1,
  },
  {
    id: 'mcq-mem-08',
    topic: 'mem',
    q: 'Quale memoria è la più lenta della gerarchia?',
    options: ['Cache L1', 'Registri', 'Memoria secondaria', 'SRAM'],
    correct: 2,
  },
  {
    id: 'mcq-mem-09',
    topic: 'mem',
    q: 'Principale svantaggio di una DRAM molto grande:',
    options: [
      'Consuma poco',
      'Ne viene compromessa la velocità',
      'È troppo veloce',
      'Non serve refresh',
    ],
    correct: 1,
  },
  {
    id: 'mcq-mem-10',
    topic: 'mem',
    q: 'Perché una cella DRAM va rinfrescata periodicamente?',
    options: [
      'Il transistor si rompe',
      'Il condensatore si scarica per correnti di dispersione',
      'Il clock si ferma',
      'La cache la sovrascrive',
    ],
    correct: 1,
  },
  {
    id: 'mcq-mem-11',
    topic: 'mem',
    q: 'La SRAM (celle della cache) rispetto alla DRAM:',
    options: [
      'Necessita di refresh',
      'Non necessita di refresh',
      'È più lenta',
      'È più densa',
    ],
    correct: 1,
  },

  {
    id: 'mcq-mem-12',
    topic: 'mem',
    q: 'Con la politica <b>write-back</b>, quando la memoria principale viene aggiornata?',
    options: [
      'A ogni scrittura, insieme alla cache',
      'Solo quando la linea modificata viene sfrattata',
      'Mai',
      'A ogni cache miss',
    ],
    correct: 1,
  },
  {
    id: 'mcq-mem-13',
    topic: 'mem',
    q: 'A che cosa serve il <b>dirty bit</b> di una linea di cache?',
    options: [
      'A indicare che la linea contiene dati non validi',
      'A segnalare che la linea è stata modificata e va riscritta in memoria',
      'A contare gli accessi alla linea',
      'A marcare la linea come non sostituibile',
    ],
    correct: 1,
  },
  {
    id: 'mcq-mem-14',
    topic: 'mem',
    q: 'In quali campi si scompone un indirizzo per accedere alla cache?',
    options: [
      'Segno, esponente, mantissa',
      'Tag, indice, offset',
      'Pagina, frame, offset',
      'Opcode, operando, modo',
    ],
    correct: 1,
  },
  {
    id: 'mcq-mem-15',
    topic: 'mem',
    q: 'Il tempo medio di accesso vale <code>t_hit + miss_rate × miss_penalty</code>. Con t_hit = 1 ns, miss rate 5% e penalità 100 ns, quanto vale?',
    options: ['1 ns', '6 ns', '100 ns', '105 ns'],
    correct: 1,
  },
  {
    id: 'mcq-mem-16',
    topic: 'mem',
    q: 'Perché la cache trasferisce blocchi e non singole parole?',
    options: [
      'Per sfruttare la località spaziale',
      'Per ridurre il numero di tag',
      'Perché la DRAM non sa leggere una sola parola',
      'Per semplificare il calcolo del dirty bit',
    ],
    correct: 0,
  },

  // ══════════════════ Memoria virtuale ══════════════════
  {
    id: 'mcq-vm-01',
    topic: 'vm',
    q: 'Nella traduzione di un indirizzo virtuale paginato, quale campo resta invariato?',
    options: [
      "L'offset nella pagina",
      'Il numero di pagina',
      'Il tag',
      'Tutti i campi vengono tradotti',
    ],
    correct: 0,
  },
  {
    id: 'mcq-vm-02',
    topic: 'vm',
    q: 'Che cosa contiene il <b>TLB</b>?',
    options: [
      'I dati usati di recente',
      'Le traduzioni pagina→frame usate di recente',
      "L'elenco dei processi attivi",
      'I blocchi sfrattati dalla cache',
    ],
    correct: 1,
  },
  {
    id: 'mcq-vm-03',
    topic: 'vm',
    q: 'Che cosa accade in caso di <b>page fault</b>?',
    options: [
      'Il programma termina con errore',
      "Si solleva un'eccezione: il SO carica la pagina da disco e riesegue l'istruzione",
      'La pagina viene creata vuota e si prosegue',
      'Il TLB viene svuotato e basta',
    ],
    correct: 1,
  },
  {
    id: 'mcq-vm-04',
    topic: 'vm',
    q: 'Senza TLB, quanti accessi in memoria costerebbe leggere un dato con memoria virtuale paginata?',
    options: [
      'Uno solo',
      'Due: uno per la tabella delle pagine e uno per il dato',
      'Nessuno',
      'Dipende dalla dimensione della cache',
    ],
    correct: 1,
  },
  {
    id: 'mcq-vm-05',
    topic: 'vm',
    q: 'Come si ottiene l’isolamento fra processi nella memoria virtuale?',
    options: [
      'Cifrando la memoria',
      'Dando a ogni processo la propria tabella delle pagine',
      'Assegnando a ogni processo una cache dedicata',
      'Disabilitando le interruzioni',
    ],
    correct: 1,
  },

  // ══════════════════ Virgola mobile ══════════════════
  {
    id: 'mcq-ieee-01',
    topic: 'ieee',
    q: 'Lo standard per la rappresentazione in virgola mobile è:',
    options: ['ASCII', 'IEEE 754', 'Unicode', 'ISO 8859'],
    correct: 1,
  },
  {
    id: 'mcq-ieee-02',
    topic: 'ieee',
    q: 'In IEEE 754 singola precisione, quanti bit hanno segno, esponente e mantissa?',
    options: ['1, 8, 23', '1, 11, 52', '1, 7, 24', '2, 8, 22'],
    correct: 0,
  },
  {
    id: 'mcq-ieee-03',
    topic: 'ieee',
    q: 'Quanto vale la polarizzazione (bias) dell’esponente in singola precisione?',
    options: ['64', '127', '128', '1023'],
    correct: 1,
  },
  {
    id: 'mcq-ieee-04',
    topic: 'ieee',
    q: 'Perché il bit «1.» davanti alla mantissa non viene memorizzato?',
    options: [
      'Perché vale sempre 1 nei numeri normalizzati, quindi si guadagna un bit di precisione',
      'Perché occuperebbe troppo spazio',
      'Perché dipende dal segno',
      'Perché lo standard lo vieta',
    ],
    correct: 0,
  },
  {
    id: 'mcq-ieee-05',
    topic: 'ieee',
    q: 'Esponente tutto a 1 e mantissa non nulla rappresentano:',
    options: ['Zero', 'Infinito', 'NaN', 'Un numero denormalizzato'],
    correct: 2,
  },

  // ══════════════════ Aritmetica hardware ══════════════════
  {
    id: 'mcq-arith-01',
    topic: 'arith',
    q: 'Quali funzioni realizza un <b>semisommatore</b>?',
    options: [
      's = a ⊕ b, c = a · b',
      's = a · b, c = a ⊕ b',
      's = a + b, c = a ⊕ b',
      's = a ⊕ b, c = a + b',
    ],
    correct: 0,
  },
  {
    id: 'mcq-arith-02',
    topic: 'arith',
    q: 'Quanti ingressi ha un <b>sommatore completo</b>?',
    options: ['2', '3 (due addendi e il riporto entrante)', '4', 'Dipende dal numero di bit'],
    correct: 1,
  },
  {
    id: 'mcq-arith-03',
    topic: 'arith',
    q: 'Perché un sommatore <b>ripple-carry</b> a n bit è lento?',
    options: [
      'Perché usa porte a molti ingressi',
      'Perché il riporto deve attraversare tutti gli n stadi in cascata',
      'Perché richiede un clock dedicato',
      'Perché somma un bit per ciclo di clock',
    ],
    correct: 1,
  },
  {
    id: 'mcq-arith-04',
    topic: 'arith',
    q: 'Nel carry-lookahead, la funzione di <b>generazione</b> vale:',
    options: ['Gᵢ = aᵢ · bᵢ', 'Gᵢ = aᵢ ⊕ bᵢ', 'Gᵢ = aᵢ + bᵢ', 'Gᵢ = aᵢ · cᵢ'],
    correct: 0,
  },
  {
    id: 'mcq-arith-05',
    topic: 'arith',
    q: 'Il prodotto di due numeri da n bit occupa al massimo:',
    options: ['n bit', 'n + 1 bit', '2n bit', '2n + 1 bit'],
    correct: 2,
  },
  {
    id: 'mcq-arith-06',
    topic: 'arith',
    q: 'Come si ottiene un sommatore/sottrattore unico in complemento a 2?',
    options: [
      'Con un secondo circuito dedicato alla sottrazione',
      'Invertendo B con degli XOR e ponendo il riporto iniziale a 1',
      'Scambiando A e B quando si sottrae',
      'Non è possibile: servono due circuiti',
    ],
    correct: 1,
  },

  // ══════════════════ Reti combinatorie notevoli ══════════════════
  {
    id: 'mcq-comb-01',
    topic: 'comb',
    q: 'Un <b>decodificatore</b> con n ingressi ha:',
    options: [
      '2ⁿ uscite, una sola attiva per volta',
      'n uscite, tutte attive',
      '2ⁿ uscite, tutte attive per volta',
      'una sola uscita',
    ],
    correct: 0,
  },
  {
    id: 'mcq-comb-02',
    topic: 'comb',
    q: 'A che cosa serve un <b>multiplexer</b>?',
    options: [
      'A convertire un numero da binario a decimale',
      'A scegliere uno fra più ingressi dati in base alle linee di selezione',
      'A memorizzare un bit',
      'A generare il riporto di una somma',
    ],
    correct: 1,
  },
  {
    id: 'mcq-comb-03',
    topic: 'comb',
    q: 'Che cos’è il <b>terzo stato</b> di un buffer tri-state?',
    options: [
      'Un livello logico intermedio fra 0 e 1',
      "L'alta impedenza: l'uscita si scollega elettricamente",
      'Uno stato di errore',
      'Un ritardo programmabile',
    ],
    correct: 1,
  },
  {
    id: 'mcq-comb-04',
    topic: 'comb',
    q: 'Perché su un bus condiviso servono uscite tri-state?',
    options: [
      'Per aumentare la velocità di trasmissione',
      'Perché due dispositivi che pilotano lo stesso filo con valori opposti lo cortocircuiterebbero',
      'Per ridurre il numero di fili',
      'Per generare il segnale di clock',
    ],
    correct: 1,
  },
  {
    id: 'mcq-comb-05',
    topic: 'comb',
    q: 'Quale porta confronta due bit segnalando con 1 che sono <b>uguali</b>?',
    options: ['XOR', 'XNOR', 'NAND', 'OR'],
    correct: 1,
  },
  {
    id: 'mcq-comb-06',
    topic: 'comb',
    q: 'Che cosa distingue un <b>priority encoder</b> da un encoder semplice?',
    options: [
      'Ha più uscite',
      'Gestisce il caso di più ingressi attivi dando la precedenza a uno',
      'Funziona senza alimentazione',
      'È sequenziale invece che combinatorio',
    ],
    correct: 1,
  },

  // ══════════════════ Tempi, tecnologia, dispositivi programmabili ══════════════════
  {
    id: 'mcq-tech-01',
    topic: 'tech',
    q: 'Il <b>ritardo di propagazione</b> di una porta si misura:',
    options: [
      "Fra il 10% e il 90% del fronte d'uscita",
      "Fra gli istanti in cui ingresso e uscita attraversano il 50% dell'escursione",
      'Fra due fronti di clock consecutivi',
      "Dal momento dell'accensione",
    ],
    correct: 1,
  },
  {
    id: 'mcq-tech-02',
    topic: 'tech',
    q: 'In una rete combinatoria con più porte <b>in cascata</b>, il ritardo complessivo:',
    options: [
      'È quello della porta più veloce',
      'È la somma dei ritardi lungo il cammino più lento (cammino critico)',
      'È sempre uguale a quello di una singola porta',
      'Si annulla se la rete è minimizzata',
    ],
    correct: 1,
  },
  {
    id: 'mcq-tech-03',
    topic: 'tech',
    q: 'Che cosa fissa il <b>periodo minimo di clock</b> di un circuito sincrono?',
    options: [
      'Il numero di flip-flop',
      'Il cammino critico fra due registri, più il tempo di setup',
      'La tensione di alimentazione',
      'Il numero di ingressi del circuito',
    ],
    correct: 1,
  },
  {
    id: 'mcq-tech-04',
    topic: 'tech',
    q: 'Il <b>fan-out</b> di una porta indica:',
    options: [
      'Quanti ingressi accetta',
      'Quante altre porte la sua uscita può pilotare',
      'Il suo ritardo di propagazione',
      'Il numero di transistor che la compongono',
    ],
    correct: 1,
  },
  {
    id: 'mcq-tech-05',
    topic: 'tech',
    q: 'In un circuito CMOS la corrente scorre in modo significativo:',
    options: [
      'Costantemente, anche a riposo',
      'Quasi solo durante le commutazioni',
      'Solo quando l’uscita vale 1',
      'Solo quando l’uscita vale 0',
    ],
    correct: 1,
  },
  {
    id: 'mcq-tech-06',
    topic: 'tech',
    q: 'Una <b>PLA</b> è organizzata come:',
    options: [
      'Una matrice di AND seguita da una matrice di OR, entrambe programmabili',
      'Una matrice di flip-flop',
      'Una memoria a sola lettura',
      'Un insieme di multiplexer in cascata',
    ],
    correct: 0,
  },

  // ══════════════════ Input/Output, DMA, bus ══════════════════
  {
    id: 'mcq-io-01',
    topic: 'io',
    q: 'Con l’I/O <b>memory-mapped</b>, per leggere un registro di interfaccia si usa:',
    options: [
      'Una istruzione dedicata IN',
      'Una normale istruzione Load',
      'Una chiamata di sistema',
      "Un'interruzione software",
    ],
    correct: 1,
  },
  {
    id: 'mcq-io-02',
    topic: 'io',
    q: 'Quante interruzioni genera tipicamente un trasferimento DMA di un blocco?',
    options: ['Una per parola trasferita', 'Una sola, a trasferimento concluso', 'Nessuna', 'Due per parola'],
    correct: 1,
  },
  {
    id: 'mcq-io-03',
    topic: 'io',
    q: 'Il difetto principale dell’I/O programmato (polling) è che:',
    options: [
      'Richiede hardware dedicato costoso',
      'Il processore consuma tempo in un ciclo di attesa',
      'Non funziona con dispositivi lenti',
      'Richiede sempre il DMA',
    ],
    correct: 1,
  },
  {
    id: 'mcq-io-04',
    topic: 'io',
    q: 'In un trasferimento con <b>handshake</b>, la velocità è quella:',
    options: [
      'Del dispositivo più veloce',
      'Del dispositivo più lento fra i due',
      'Del clock di sistema',
      'Fissata dal bus, indipendente dai dispositivi',
    ],
    correct: 1,
  },
  {
    id: 'mcq-io-05',
    topic: 'io',
    q: 'Quale problema introduce il DMA rispetto alla cache?',
    options: [
      'Rallenta il clock del processore',
      'Scrivendo in memoria può rendere obsoleta la copia in cache (coerenza)',
      'Impedisce le interruzioni',
      'Richiede di disabilitare la memoria virtuale',
    ],
    correct: 1,
  },
  {
    id: 'mcq-io-06',
    topic: 'io',
    q: 'Perché gli standard moderni ad alta velocità (USB, PCI Express) sono <b>seriali</b>?',
    options: [
      'Perché il parallelo non permette il controllo di errore',
      'Meno fili, meno interferenze e nessuno sfasamento fra le linee: si sale in frequenza',
      'Perché costano di più',
      'Perché il seriale trasferisce più bit per volta',
    ],
    correct: 1,
  },
  // ── dal sorgente all'esecuzione ──
  {
    id: 'mcq-sw-01',
    topic: 'sw',
    q: 'Perché un assemblatore lavora in <b>due passate</b>?',
    options: [
      'Per controllare due volte la sintassi',
      'Perché nella prima passata costruisce la tabella dei simboli, e solo allora può risolvere i salti in avanti',
      'Perché deve tradurre prima i dati e poi le istruzioni',
      'Per ottimizzare il codice generato',
    ],
    correct: 1,
  },
  {
    id: 'mcq-sw-02',
    topic: 'sw',
    q: 'Che cosa produce la direttiva <code>DATAWORD 42</code>?',
    options: [
      'Un\u2019istruzione che carica 42 in un registro',
      'Una parola di memoria inizializzata a 42, non un\u2019istruzione',
      'Una costante simbolica utilizzabile nel sorgente',
      'Una riserva di 42 byte non inizializzati',
    ],
    correct: 1,
  },
  {
    id: 'mcq-sw-03',
    topic: 'sw',
    q: 'Di che cosa si occupa il <b>collegatore</b> (linker)?',
    options: [
      'Di tradurre i mnemonici in codici operativi',
      'Di risolvere i riferimenti esterni fra moduli oggetto e librerie, producendo l\u2019eseguibile',
      'Di copiare il programma in memoria e avviarlo',
      'Di allocare la memoria ai processi durante l\u2019esecuzione',
    ],
    correct: 1,
  },
  {
    id: 'mcq-sw-04',
    topic: 'sw',
    q: 'In quali casi il sistema operativo riprende il controllo del processore?',
    options: [
      'In continuazione, perché gira in parallelo al programma utente',
      'Solo su chiamata di sistema, interruzione o eccezione',
      'A ogni istruzione, che verifica prima di eseguirla',
      'Solo quando il programma termina',
    ],
    correct: 1,
  },

  // ── prestazioni e parallelismo ──
  {
    id: 'mcq-perf-01',
    topic: 'perf',
    q: 'Nell\u2019equazione <code>T = (N \u00d7 S) / R</code>, che cosa rappresenta <code>S</code>?',
    options: [
      'La dimensione della cache',
      'Il numero medio di cicli di clock per istruzione',
      'Il numero di stadi della pipeline',
      'La frequenza di clock in GHz',
    ],
    correct: 1,
  },
  {
    id: 'mcq-perf-02',
    topic: 'perf',
    q: 'Il 50 % del tempo di esecuzione viene reso <b>4 volte</b> più veloce. Qual è il guadagno complessivo?',
    options: ['4\u00d7', '1,6\u00d7', '2\u00d7', '2,5\u00d7'],
    correct: 1,
  },
  {
    id: 'mcq-perf-03',
    topic: 'perf',
    q: 'Perché i <b>MIPS</b> sono una misura poco affidabile per confrontare due processori?',
    options: [
      'Perché non tengono conto della frequenza di clock',
      'Perché dipendono dal repertorio di istruzioni e dal programma: la stessa quantit\u00e0 di lavoro richiede pi\u00f9 istruzioni su una macchina che sull\u2019altra',
      'Perché misurano solo le operazioni in virgola mobile',
      'Perché sono definiti solo per le macchine RISC',
    ],
    correct: 1,
  },
  {
    id: 'mcq-perf-04',
    topic: 'perf',
    q: 'Qual è la ragione <b>fisica</b> per cui si è passati dall\u2019alzare la frequenza al mettere pi\u00f9 core?',
    options: [
      'I transistor non si possono pi\u00f9 rimpicciolire',
      'Il consumo dinamico cresce con f\u00b7C\u00b7V\u00b2: alzare la frequenza costa in potenza e calore molto pi\u00f9 che aggiungere core',
      'I programmi sono tutti gi\u00e0 paralleli',
      'La memoria non riesce a seguire una sola pipeline',
    ],
    correct: 1,
  },
];